#include <AP_Param/AP_Param.h>
#include "MatlabController.h"


const AP_Param::GroupInfo MatlabControllerClass::var_info_1[] = {
  AP_GROUPINFO("cef_cla1", 0, MatlabControllerClass, rtP.lindi.cef.cla[0], 5.093640e+00),
  AP_GROUPINFO("cef_cla2", 1, MatlabControllerClass, rtP.lindi.cef.cla[1], 5.093640e+00),
  AP_GROUPINFO("cef_cla3", 2, MatlabControllerClass, rtP.lindi.cef.cla[2], 5.093640e+00),
  AP_GROUPINFO("cef_cla4", 3, MatlabControllerClass, rtP.lindi.cef.cla[3], 5.093640e+00),
  AP_GROUPINFO("cef_cla5", 4, MatlabControllerClass, rtP.lindi.cef.cla[4], 5.093640e+00),
  AP_GROUPINFO("cef_cla6", 5, MatlabControllerClass, rtP.lindi.cef.cla[5], 5.093640e+00),
  AP_GROUPINFO("cef_cla7", 6, MatlabControllerClass, rtP.lindi.cef.cla[6], 5.093640e+00),
  AP_GROUPINFO("cef_cla8", 7, MatlabControllerClass, rtP.lindi.cef.cla[7], 5.093640e+00),
  AP_GROUPINFO("cef_cla9", 8, MatlabControllerClass, rtP.lindi.cef.cla[8], 4.080931e+00),
  AP_GROUPINFO("cef_cla10", 9, MatlabControllerClass, rtP.lindi.cef.cla[9], 2.253448e+00),
  AP_GROUPINFO("cef_dadf1", 10, MatlabControllerClass, rtP.lindi.cef.dadf[0], 9.598081e-02),
  AP_GROUPINFO("cef_dadf2", 11, MatlabControllerClass, rtP.lindi.cef.dadf[1], 1.252387e-01),
  AP_GROUPINFO("cef_dadf3", 12, MatlabControllerClass, rtP.lindi.cef.dadf[2], 1.223527e-01),
  AP_GROUPINFO("cef_dadf4", 13, MatlabControllerClass, rtP.lindi.cef.dadf[3], 1.514653e-01),
  AP_GROUPINFO("cef_dadf5", 14, MatlabControllerClass, rtP.lindi.cef.dadf[4], 1.514653e-01),
  AP_GROUPINFO("cef_dadf6", 15, MatlabControllerClass, rtP.lindi.cef.dadf[5], 1.223527e-01),
  AP_GROUPINFO("cef_dadf7", 16, MatlabControllerClass, rtP.lindi.cef.dadf[6], 1.252387e-01),
  AP_GROUPINFO("cef_dadf8", 17, MatlabControllerClass, rtP.lindi.cef.dadf[7], 9.598081e-02),
  AP_GROUPINFO("cef_dadf9", 18, MatlabControllerClass, rtP.lindi.cef.dadf[8], 6.186650e-01),
  AP_GROUPINFO("cef_dadf10", 19, MatlabControllerClass, rtP.lindi.cef.dadf[9], 7.853041e-01),
  AP_GROUPINFO("cef_dfdu1", 20, MatlabControllerClass, rtP.lindi.cef.dfdu[0], 4.886922e-01),
  AP_GROUPINFO("cef_dfdu2", 21, MatlabControllerClass, rtP.lindi.cef.dfdu[1], 4.886922e-01),
  AP_GROUPINFO("cef_dfdu3", 22, MatlabControllerClass, rtP.lindi.cef.dfdu[2], 4.886922e-01),
  AP_GROUPINFO("cef_dfdu4", 23, MatlabControllerClass, rtP.lindi.cef.dfdu[3], 4.886922e-01),
  AP_GROUPINFO("cef_dfdu5", 24, MatlabControllerClass, rtP.lindi.cef.dfdu[4], 4.886922e-01),
  AP_GROUPINFO("cef_dfdu6", 25, MatlabControllerClass, rtP.lindi.cef.dfdu[5], 4.886922e-01),
  AP_GROUPINFO("cef_dfdu7", 26, MatlabControllerClass, rtP.lindi.cef.dfdu[6], 4.886922e-01),
  AP_GROUPINFO("cef_dfdu8", 27, MatlabControllerClass, rtP.lindi.cef.dfdu[7], 4.886922e-01),
  AP_GROUPINFO("cef_dfdu9", 28, MatlabControllerClass, rtP.lindi.cef.dfdu[8], 3.665192e-01),
  AP_GROUPINFO("cef_dfdu10", 29, MatlabControllerClass, rtP.lindi.cef.dfdu[9], 4.712389e-01),
  AP_GROUPINFO("cef_s1", 30, MatlabControllerClass, rtP.lindi.cef.s[0], 1.852975e-01),
  AP_GROUPINFO("cef_s2", 31, MatlabControllerClass, rtP.lindi.cef.s[1], 1.852975e-01),
  AP_GROUPINFO("cef_s3", 32, MatlabControllerClass, rtP.lindi.cef.s[2], 1.852975e-01),
  AP_GROUPINFO("cef_s4", 33, MatlabControllerClass, rtP.lindi.cef.s[3], 1.852975e-01),
  AP_GROUPINFO("cef_s5", 34, MatlabControllerClass, rtP.lindi.cef.s[4], 1.852975e-01),
  AP_GROUPINFO("cef_s6", 35, MatlabControllerClass, rtP.lindi.cef.s[5], 1.852975e-01),
  AP_GROUPINFO("cef_s7", 36, MatlabControllerClass, rtP.lindi.cef.s[6], 1.852975e-01),
  AP_GROUPINFO("cef_s8", 37, MatlabControllerClass, rtP.lindi.cef.s[7], 1.852975e-01),
  AP_GROUPINFO("cef_s9", 38, MatlabControllerClass, rtP.lindi.cef.s[8], 5.410600e-02),
  AP_GROUPINFO("cef_s10", 39, MatlabControllerClass, rtP.lindi.cef.s[9], 4.620000e-02),
  AP_GROUPINFO("cef_rotx1", 40, MatlabControllerClass, rtP.lindi.cef.rotx[0], 0),
  AP_GROUPINFO("cef_rotx2", 41, MatlabControllerClass, rtP.lindi.cef.rotx[1], 0),
  AP_GROUPINFO("cef_rotx3", 42, MatlabControllerClass, rtP.lindi.cef.rotx[2], 0),
  AP_GROUPINFO("cef_rotx4", 43, MatlabControllerClass, rtP.lindi.cef.rotx[3], 0),
  AP_GROUPINFO("cef_rotx5", 44, MatlabControllerClass, rtP.lindi.cef.rotx[4], 0),
  AP_GROUPINFO("cef_rotx6", 45, MatlabControllerClass, rtP.lindi.cef.rotx[5], 0),
  AP_GROUPINFO("cef_rotx7", 46, MatlabControllerClass, rtP.lindi.cef.rotx[6], 0),
  AP_GROUPINFO("cef_rotx8", 47, MatlabControllerClass, rtP.lindi.cef.rotx[7], 0),
  AP_GROUPINFO("cef_rotx9", 48, MatlabControllerClass, rtP.lindi.cef.rotx[8], 0),
  AP_GROUPINFO("cef_rotx10", 49, MatlabControllerClass, rtP.lindi.cef.rotx[9], 1.570796e+00),
  AP_GROUPINFO("cef_x1", 50, MatlabControllerClass, rtP.lindi.cef.x[0], -2.580612e-02),
  AP_GROUPINFO("cef_x2", 51, MatlabControllerClass, rtP.lindi.cef.x[1], -3.036353e-02),
  AP_GROUPINFO("cef_x3", 52, MatlabControllerClass, rtP.lindi.cef.x[2], -3.932894e-02),
  AP_GROUPINFO("cef_x4", 53, MatlabControllerClass, rtP.lindi.cef.x[3], -4.228648e-02),
  AP_GROUPINFO("cef_x5", 54, MatlabControllerClass, rtP.lindi.cef.x[4], -4.228648e-02),
  AP_GROUPINFO("cef_x6", 55, MatlabControllerClass, rtP.lindi.cef.x[5], -3.932894e-02),
  AP_GROUPINFO("cef_x7", 56, MatlabControllerClass, rtP.lindi.cef.x[6], -3.036353e-02),
  AP_GROUPINFO("cef_x8", 57, MatlabControllerClass, rtP.lindi.cef.x[7], -2.580612e-02),
  AP_GROUPINFO("cef_x9", 58, MatlabControllerClass, rtP.lindi.cef.x[8], -7.130339e-01),
  AP_GROUPINFO("cef_x10", 59, MatlabControllerClass, rtP.lindi.cef.x[9], -7.427137e-01),
  AP_GROUPEND
};


const AP_Param::GroupInfo MatlabControllerClass::var_info_2[] = {
  AP_GROUPINFO("cef_y1", 0, MatlabControllerClass, rtP.lindi.cef.y[0], -6.571736e-01),
  AP_GROUPINFO("cef_y2", 1, MatlabControllerClass, rtP.lindi.cef.y[1], -4.808912e-01),
  AP_GROUPINFO("cef_y3", 2, MatlabControllerClass, rtP.lindi.cef.y[2], -3.157907e-01),
  AP_GROUPINFO("cef_y4", 3, MatlabControllerClass, rtP.lindi.cef.y[3], -1.542614e-01),
  AP_GROUPINFO("cef_y5", 4, MatlabControllerClass, rtP.lindi.cef.y[4], 1.542614e-01),
  AP_GROUPINFO("cef_y6", 5, MatlabControllerClass, rtP.lindi.cef.y[5], 3.157907e-01),
  AP_GROUPINFO("cef_y7", 6, MatlabControllerClass, rtP.lindi.cef.y[6], 4.808912e-01),
  AP_GROUPINFO("cef_y8", 7, MatlabControllerClass, rtP.lindi.cef.y[7], 6.571736e-01),
  AP_GROUPINFO("cef_y9", 8, MatlabControllerClass, rtP.lindi.cef.y[8], -2.081668e-17),
  AP_GROUPINFO("cef_y10", 9, MatlabControllerClass, rtP.lindi.cef.y[9], -1.387779e-17),
  AP_GROUPINFO("cef_z1", 10, MatlabControllerClass, rtP.lindi.cef.z[0], -5.000000e-02),
  AP_GROUPINFO("cef_z2", 11, MatlabControllerClass, rtP.lindi.cef.z[1], -5.000000e-02),
  AP_GROUPINFO("cef_z3", 12, MatlabControllerClass, rtP.lindi.cef.z[2], -5.000000e-02),
  AP_GROUPINFO("cef_z4", 13, MatlabControllerClass, rtP.lindi.cef.z[3], -5.000000e-02),
  AP_GROUPINFO("cef_z5", 14, MatlabControllerClass, rtP.lindi.cef.z[4], -5.000000e-02),
  AP_GROUPINFO("cef_z6", 15, MatlabControllerClass, rtP.lindi.cef.z[5], -5.000000e-02),
  AP_GROUPINFO("cef_z7", 16, MatlabControllerClass, rtP.lindi.cef.z[6], -5.000000e-02),
  AP_GROUPINFO("cef_z8", 17, MatlabControllerClass, rtP.lindi.cef.z[7], -5.000000e-02),
  AP_GROUPINFO("cef_z9", 18, MatlabControllerClass, rtP.lindi.cef.z[8], -4.000000e-02),
  AP_GROUPINFO("cef_z10", 19, MatlabControllerClass, rtP.lindi.cef.z[9], -1.000000e-01),
  AP_GROUPINFO("cef_m1", 20, MatlabControllerClass, rtP.lindi.cef.m[0], 0),
  AP_GROUPINFO("cef_m2", 21, MatlabControllerClass, rtP.lindi.cef.m[1], 0),
  AP_GROUPINFO("cef_m3", 22, MatlabControllerClass, rtP.lindi.cef.m[2], 0),
  AP_GROUPINFO("cef_m4", 23, MatlabControllerClass, rtP.lindi.cef.m[3], 0),
  AP_GROUPINFO("cef_m5", 24, MatlabControllerClass, rtP.lindi.cef.m[4], 0),
  AP_GROUPINFO("cef_m6", 25, MatlabControllerClass, rtP.lindi.cef.m[5], 0),
  AP_GROUPINFO("cef_m7", 26, MatlabControllerClass, rtP.lindi.cef.m[6], 0),
  AP_GROUPINFO("cef_m8", 27, MatlabControllerClass, rtP.lindi.cef.m[7], 0),
  AP_GROUPINFO("cef_m9", 28, MatlabControllerClass, rtP.lindi.cef.m[8], 0),
  AP_GROUPINFO("cef_m10", 29, MatlabControllerClass, rtP.lindi.cef.m[9], 0),
  AP_GROUPINFO("cef_xm1", 30, MatlabControllerClass, rtP.lindi.cef.xm[0], 0),
  AP_GROUPINFO("cef_xm2", 31, MatlabControllerClass, rtP.lindi.cef.xm[1], 0),
  AP_GROUPINFO("cef_xm3", 32, MatlabControllerClass, rtP.lindi.cef.xm[2], 0),
  AP_GROUPINFO("cef_xm4", 33, MatlabControllerClass, rtP.lindi.cef.xm[3], 0),
  AP_GROUPINFO("cef_xm5", 34, MatlabControllerClass, rtP.lindi.cef.xm[4], 0),
  AP_GROUPINFO("cef_xm6", 35, MatlabControllerClass, rtP.lindi.cef.xm[5], 0),
  AP_GROUPINFO("cef_xm7", 36, MatlabControllerClass, rtP.lindi.cef.xm[6], 0),
  AP_GROUPINFO("cef_xm8", 37, MatlabControllerClass, rtP.lindi.cef.xm[7], 0),
  AP_GROUPINFO("cef_xm9", 38, MatlabControllerClass, rtP.lindi.cef.xm[8], 0),
  AP_GROUPINFO("cef_xm10", 39, MatlabControllerClass, rtP.lindi.cef.xm[9], 0),
  AP_GROUPINFO("ceb_m", 40, MatlabControllerClass, rtP.lindi.ceb.m, 2.330000e+00),
  AP_GROUPINFO("ceb_ixx", 41, MatlabControllerClass, rtP.lindi.ceb.ixx, 2.185000e-01),
  AP_GROUPINFO("ceb_iyy", 42, MatlabControllerClass, rtP.lindi.ceb.iyy, 1.783000e-01),
  AP_GROUPINFO("ceb_izz", 43, MatlabControllerClass, rtP.lindi.ceb.izz, 3.920000e-01),
  AP_GROUPINFO("ceb_ixy", 44, MatlabControllerClass, rtP.lindi.ceb.ixy, 0),
  AP_GROUPINFO("ceb_ixz", 45, MatlabControllerClass, rtP.lindi.ceb.ixz, 0),
  AP_GROUPINFO("ceb_iyz", 46, MatlabControllerClass, rtP.lindi.ceb.iyz, 0),
  AP_GROUPINFO("ceb_scale", 47, MatlabControllerClass, rtP.lindi.ceb.scale, 1.200000e+00),
  AP_GROUPINFO("servo_omega", 48, MatlabControllerClass, rtP.lindi.servo.omega, 150),
  AP_GROUPINFO("servo_boost", 49, MatlabControllerClass, rtP.lindi.servo.boost, 5.000000e-01),
  AP_GROUPINFO("sflt_omega", 50, MatlabControllerClass, rtP.lindi.sflt.omega, 50),
  AP_GROUPINFO("sflt_d", 51, MatlabControllerClass, rtP.lindi.sflt.d, 1),
  AP_GROUPINFO("aspd_flttc", 52, MatlabControllerClass, rtP.lindi.aspd.flttc, 1.000000e-01),
  AP_GROUPINFO("aspd_min", 53, MatlabControllerClass, rtP.lindi.aspd.min, 1.003482e+01),
  AP_GROUPINFO("atc_k_rang", 54, MatlabControllerClass, rtP.lindi.atc.k.rang, 27),
  AP_GROUPINFO("atc_k_rrat", 55, MatlabControllerClass, rtP.lindi.atc.k.rrat, 9),
  AP_GROUPINFO("atc_k_racc", 56, MatlabControllerClass, rtP.lindi.atc.k.racc, 2.000000e-01),
  AP_GROUPINFO("atc_k_pang", 57, MatlabControllerClass, rtP.lindi.atc.k.pang, 27),
  AP_GROUPINFO("atc_k_prat", 58, MatlabControllerClass, rtP.lindi.atc.k.prat, 9),
  AP_GROUPINFO("atc_k_pacc", 59, MatlabControllerClass, rtP.lindi.atc.k.pacc, 2.000000e-01),
  AP_GROUPINFO("atc_k_yrat", 60, MatlabControllerClass, rtP.lindi.atc.k.yrat, 3.750000e+00),
  AP_GROUPINFO("atc_k_yacc", 61, MatlabControllerClass, rtP.lindi.atc.k.yacc, 0),
  AP_GROUPINFO("atc_rm_rfreq", 62, MatlabControllerClass, rtP.lindi.atc.rm.rfreq, 9),
  AP_GROUPEND
};


const AP_Param::GroupInfo MatlabControllerClass::var_info_3[] = {
  AP_GROUPINFO("atc_rm_rangmx", 0, MatlabControllerClass, rtP.lindi.atc.rm.rangmax, 70),
  AP_GROUPINFO("atc_rm_rratmx", 1, MatlabControllerClass, rtP.lindi.atc.rm.rratmax, 70),
  AP_GROUPINFO("atc_rm_pfreq", 2, MatlabControllerClass, rtP.lindi.atc.rm.pfreq, 4.500000e+00),
  AP_GROUPINFO("atc_rm_pangmx", 3, MatlabControllerClass, rtP.lindi.atc.rm.pangmax, 30),
  AP_GROUPINFO("atc_rm_pratmx", 4, MatlabControllerClass, rtP.lindi.atc.rm.pratmax, 60),
  AP_GROUPINFO("atc_rm_yfreq", 5, MatlabControllerClass, rtP.lindi.atc.rm.yfreq, 4.500000e+00),
  AP_GROUPINFO("atc_rm_yratmx", 6, MatlabControllerClass, rtP.lindi.atc.rm.yratmax, 60),
  AP_GROUPINFO("atc_rm_ydcytc", 7, MatlabControllerClass, rtP.lindi.atc.rm.ydecaytc, 4.444444e-01),
  AP_GROUPINFO("eig_clp", 8, MatlabControllerClass, rtP.lindi.eig.clp, -5.588555e-01),
  AP_GROUPINFO("eig_b", 9, MatlabControllerClass, rtP.lindi.eig.b, 2),
  AP_GROUPINFO("eig_s", 10, MatlabControllerClass, rtP.lindi.eig.s, 3.705950e-01),
  AP_GROUPINFO("eig_claH", 11, MatlabControllerClass, rtP.lindi.eig.cla_h, 4.080931e+00),
  AP_GROUPINFO("eig_xH", 12, MatlabControllerClass, rtP.lindi.eig.x_h, 7.130339e-01),
  AP_GROUPINFO("eig_sH", 13, MatlabControllerClass, rtP.lindi.eig.s_h, 5.410600e-02),
  AP_GROUPINFO("psc_k_pos", 14, MatlabControllerClass, rtP.lindi.psc.k.pos, 8.321006e-01),
  AP_GROUPINFO("psc_k_vel", 15, MatlabControllerClass, rtP.lindi.psc.k.vel, 1.442308e+00),
  AP_GROUPINFO("psc_k_acc", 16, MatlabControllerClass, rtP.lindi.psc.k.acc, -9.480131e-16),
  AP_GROUPINFO("psc_rm_T", 17, MatlabControllerClass, rtP.lindi.psc.rm.T, 6.666667e-01),
  AP_GROUPINFO("psc_rm_wprad", 18, MatlabControllerClass, rtP.lindi.psc.rm.wprad, 60),
  AP_GROUPINFO("psc_rm_eposmx", 19, MatlabControllerClass, rtP.lindi.psc.rm.eposmax, 20),
  AP_GROUPINFO("ca_uMin1", 20, MatlabControllerClass, rtP.lindi.ca.u_min[0], -1),
  AP_GROUPINFO("ca_uMin2", 21, MatlabControllerClass, rtP.lindi.ca.u_min[1], -1),
  AP_GROUPINFO("ca_uMin3", 22, MatlabControllerClass, rtP.lindi.ca.u_min[2], -1),
  AP_GROUPINFO("ca_uMin4", 23, MatlabControllerClass, rtP.lindi.ca.u_min[3], -1),
  AP_GROUPINFO("ca_uMin5", 24, MatlabControllerClass, rtP.lindi.ca.u_min[4], -1),
  AP_GROUPINFO("ca_uMin6", 25, MatlabControllerClass, rtP.lindi.ca.u_min[5], -1),
  AP_GROUPINFO("ca_uMin7", 26, MatlabControllerClass, rtP.lindi.ca.u_min[6], -1),
  AP_GROUPINFO("ca_uMin8", 27, MatlabControllerClass, rtP.lindi.ca.u_min[7], -1),
  AP_GROUPINFO("ca_uMin9", 28, MatlabControllerClass, rtP.lindi.ca.u_min[8], -1),
  AP_GROUPINFO("ca_uMin10", 29, MatlabControllerClass, rtP.lindi.ca.u_min[9], -1),
  AP_GROUPINFO("ca_uMax1", 30, MatlabControllerClass, rtP.lindi.ca.u_max[0], 1),
  AP_GROUPINFO("ca_uMax2", 31, MatlabControllerClass, rtP.lindi.ca.u_max[1], 1),
  AP_GROUPINFO("ca_uMax3", 32, MatlabControllerClass, rtP.lindi.ca.u_max[2], 1),
  AP_GROUPINFO("ca_uMax4", 33, MatlabControllerClass, rtP.lindi.ca.u_max[3], 1),
  AP_GROUPINFO("ca_uMax5", 34, MatlabControllerClass, rtP.lindi.ca.u_max[4], 1),
  AP_GROUPINFO("ca_uMax6", 35, MatlabControllerClass, rtP.lindi.ca.u_max[5], 1),
  AP_GROUPINFO("ca_uMax7", 36, MatlabControllerClass, rtP.lindi.ca.u_max[6], 1),
  AP_GROUPINFO("ca_uMax8", 37, MatlabControllerClass, rtP.lindi.ca.u_max[7], 1),
  AP_GROUPINFO("ca_uMax9", 38, MatlabControllerClass, rtP.lindi.ca.u_max[8], 1),
  AP_GROUPINFO("ca_uMax10", 39, MatlabControllerClass, rtP.lindi.ca.u_max[9], 1),
  AP_GROUPINFO("ca_uD1", 40, MatlabControllerClass, rtP.lindi.ca.u_d[0], 0),
  AP_GROUPINFO("ca_uD2", 41, MatlabControllerClass, rtP.lindi.ca.u_d[1], 0),
  AP_GROUPINFO("ca_uD3", 42, MatlabControllerClass, rtP.lindi.ca.u_d[2], 0),
  AP_GROUPINFO("ca_uD4", 43, MatlabControllerClass, rtP.lindi.ca.u_d[3], 0),
  AP_GROUPINFO("ca_uD5", 44, MatlabControllerClass, rtP.lindi.ca.u_d[4], 0),
  AP_GROUPINFO("ca_uD6", 45, MatlabControllerClass, rtP.lindi.ca.u_d[5], 0),
  AP_GROUPINFO("ca_uD7", 46, MatlabControllerClass, rtP.lindi.ca.u_d[6], 0),
  AP_GROUPINFO("ca_uD8", 47, MatlabControllerClass, rtP.lindi.ca.u_d[7], 0),
  AP_GROUPINFO("ca_uD9", 48, MatlabControllerClass, rtP.lindi.ca.u_d[8], 0),
  AP_GROUPINFO("ca_uD10", 49, MatlabControllerClass, rtP.lindi.ca.u_d[9], 0),
  AP_GROUPINFO("ca_Wv1", 50, MatlabControllerClass, rtP.lindi.ca.W_v[0], 10),
  AP_GROUPINFO("ca_Wv2", 51, MatlabControllerClass, rtP.lindi.ca.W_v[1], 1),
  AP_GROUPINFO("ca_Wv3", 52, MatlabControllerClass, rtP.lindi.ca.W_v[2], 1.000000e-01),
  AP_GROUPINFO("ca_Wu1", 53, MatlabControllerClass, rtP.lindi.ca.W_u[0], 1),
  AP_GROUPINFO("ca_Wu2", 54, MatlabControllerClass, rtP.lindi.ca.W_u[1], 1),
  AP_GROUPINFO("ca_Wu3", 55, MatlabControllerClass, rtP.lindi.ca.W_u[2], 1),
  AP_GROUPINFO("ca_Wu4", 56, MatlabControllerClass, rtP.lindi.ca.W_u[3], 1),
  AP_GROUPINFO("ca_Wu5", 57, MatlabControllerClass, rtP.lindi.ca.W_u[4], 1),
  AP_GROUPINFO("ca_Wu6", 58, MatlabControllerClass, rtP.lindi.ca.W_u[5], 1),
  AP_GROUPINFO("ca_Wu7", 59, MatlabControllerClass, rtP.lindi.ca.W_u[6], 1),
  AP_GROUPINFO("ca_Wu8", 60, MatlabControllerClass, rtP.lindi.ca.W_u[7], 1),
  AP_GROUPINFO("ca_Wu9", 61, MatlabControllerClass, rtP.lindi.ca.W_u[8], 1),
  AP_GROUPINFO("ca_Wu10", 62, MatlabControllerClass, rtP.lindi.ca.W_u[9], 1),
  AP_GROUPEND
};


const AP_Param::GroupInfo MatlabControllerClass::var_info_4[] = {
  AP_GROUPINFO("ca_gamma", 0, MatlabControllerClass, rtP.lindi.ca.gamma, 1000),
  AP_GROUPINFO("ca_W1", 1, MatlabControllerClass, rtP.lindi.ca.W[0], 0),
  AP_GROUPINFO("ca_W2", 2, MatlabControllerClass, rtP.lindi.ca.W[1], 0),
  AP_GROUPINFO("ca_W3", 3, MatlabControllerClass, rtP.lindi.ca.W[2], 0),
  AP_GROUPINFO("ca_W4", 4, MatlabControllerClass, rtP.lindi.ca.W[3], 0),
  AP_GROUPINFO("ca_W5", 5, MatlabControllerClass, rtP.lindi.ca.W[4], 0),
  AP_GROUPINFO("ca_W6", 6, MatlabControllerClass, rtP.lindi.ca.W[5], 0),
  AP_GROUPINFO("ca_W7", 7, MatlabControllerClass, rtP.lindi.ca.W[6], 0),
  AP_GROUPINFO("ca_W8", 8, MatlabControllerClass, rtP.lindi.ca.W[7], 0),
  AP_GROUPINFO("ca_W9", 9, MatlabControllerClass, rtP.lindi.ca.W[8], 0),
  AP_GROUPINFO("ca_W10", 10, MatlabControllerClass, rtP.lindi.ca.W[9], 0),
  AP_GROUPINFO("ca_iMax", 11, MatlabControllerClass, rtP.lindi.ca.i_max, 15),
  AP_GROUPINFO("mla_use", 12, MatlabControllerClass, rtP.lindi.mla.use, 0),
  AP_GROUPINFO("mla_etaNp1", 13, MatlabControllerClass, rtP.lindi.mla.eta_np[0], -4.292534e-01),
  AP_GROUPINFO("mla_etaNp2", 14, MatlabControllerClass, rtP.lindi.mla.eta_np[1], 4.292534e-01),
  AP_GROUPINFO("mla_ca_Wv1", 15, MatlabControllerClass, rtP.lindi.mla.ca.W_v[0], 1),
  AP_GROUPINFO("mla_ca_Wv2", 16, MatlabControllerClass, rtP.lindi.mla.ca.W_v[1], 1),
  AP_GROUPINFO("mla_ca_Wv3", 17, MatlabControllerClass, rtP.lindi.mla.ca.W_v[2], 10),
  AP_GROUPINFO("mla_ca_Wu1", 18, MatlabControllerClass, rtP.lindi.mla.ca.W_u[0], 1),
  AP_GROUPINFO("mla_ca_Wu2", 19, MatlabControllerClass, rtP.lindi.mla.ca.W_u[1], 1),
  AP_GROUPINFO("mla_ca_Wu3", 20, MatlabControllerClass, rtP.lindi.mla.ca.W_u[2], 1),
  AP_GROUPINFO("mla_ca_Wu4", 21, MatlabControllerClass, rtP.lindi.mla.ca.W_u[3], 1),
  AP_GROUPINFO("mla_ca_Wu5", 22, MatlabControllerClass, rtP.lindi.mla.ca.W_u[4], 1),
  AP_GROUPINFO("mla_ca_Wu6", 23, MatlabControllerClass, rtP.lindi.mla.ca.W_u[5], 1),
  AP_GROUPINFO("mla_ca_Wu7", 24, MatlabControllerClass, rtP.lindi.mla.ca.W_u[6], 1),
  AP_GROUPINFO("mla_ca_Wu8", 25, MatlabControllerClass, rtP.lindi.mla.ca.W_u[7], 1),
  AP_GROUPINFO("mla_ca_Wu9", 26, MatlabControllerClass, rtP.lindi.mla.ca.W_u[8], 1),
  AP_GROUPINFO("mla_ca_Wu10", 27, MatlabControllerClass, rtP.lindi.mla.ca.W_u[9], 1),
  AP_GROUPINFO("mla_ca_gamma", 28, MatlabControllerClass, rtP.lindi.mla.ca.gamma, 1000),
  AP_GROUPINFO("mla_ca_iMax", 29, MatlabControllerClass, rtP.lindi.mla.ca.i_max, 15),
  AP_GROUPEND
};


const AP_Param::GroupInfo MatlabControllerClass::var_info[] = {
  AP_SUBGROUPEXTENSION("", 0, MatlabControllerClass, var_info_1),
  AP_SUBGROUPEXTENSION("", 1, MatlabControllerClass, var_info_2),
  AP_SUBGROUPEXTENSION("", 2, MatlabControllerClass, var_info_3),
  AP_SUBGROUPEXTENSION("", 3, MatlabControllerClass, var_info_4),
  AP_GROUPEND
};
